// SPDX-License-Identifier: MIT

use std::sync::Arc;
use aegis_gateway::core::approval::ApprovalGate;
use aegis_gateway::core::data_governance::{
    DataClassification, DataEgressDecision, DataEgressPolicyEngine, InSituDataEnclave, PolicyTier,
};
use aegis_gateway::core::types::{CallerContext, TenantId};
use aegis_gateway::policy::{ActionApprovalGate, TieredDataEgressEngine};
use aegis_gateway::sandbox::{HermeticProcessSandbox, SandboxedInSituEnclave};
use aegis_gateway::sandbox::egress_firewall::EgressFilterEngine;
use aegis_gateway::sandbox::credential_broker::VaultCredentialBroker;
use aegis_gateway::policy::secrets::EnvSecretStore;
use aegis_gateway::audit::StructuredAuditLogger;

fn make_test_caller() -> CallerContext {
    CallerContext {
        tenant_id: TenantId::new("enterprise-analytics"),
        subject: "alice@company.com".to_string(),
        roles: vec!["analyst".to_string()],
        department: Some("data_science".to_string()),
        client_ip: None,
        session_id: "test-sess-001".to_string(),
    }
}

#[tokio::test]
async fn test_policy_tier_developer_allows_direct_egress_unconditionally() {
    let gate: Arc<dyn ApprovalGate> = Arc::new(ActionApprovalGate::new("dev_secret_key"));
    let engine = TieredDataEgressEngine::new(PolicyTier::Developer, 10 * 1024 * 1024, Some(gate));
    let caller = make_test_caller();

    // Large 105MB raw dataset
    let decision = engine
        .evaluate_egress(
            "export_parquet.zip",
            105 * 1024 * 1024,
            "application/zip",
            DataClassification::RawRestricted,
            &caller,
        )
        .await
        .expect("Egress evaluation should succeed");

    assert_eq!(decision, DataEgressDecision::AllowDirectEgress);
}

#[tokio::test]
async fn test_policy_tier_hybrid_enforces_size_threshold_and_approval() {
    let gate: Arc<dyn ApprovalGate> = Arc::new(ActionApprovalGate::new("hybrid_secret_key"));
    let engine = TieredDataEgressEngine::new(PolicyTier::Hybrid, 10 * 1024 * 1024, Some(gate));
    let caller = make_test_caller();

    // 1. Small file under 10MB -> Allowed directly
    let small_decision = engine
        .evaluate_egress(
            "sample_snippet.csv",
            2 * 1024 * 1024,
            "text/csv",
            DataClassification::RawRestricted,
            &caller,
        )
        .await
        .expect("Evaluation should succeed");
    assert_eq!(small_decision, DataEgressDecision::AllowDirectEgress);

    // 2. Large raw dataset (105MB) -> Requires Managerial Approval (HITL)
    let large_raw_decision = engine
        .evaluate_egress(
            "export_parquet.zip",
            105 * 1024 * 1024,
            "application/zip",
            DataClassification::RawRestricted,
            &caller,
        )
        .await
        .expect("Evaluation should succeed");

    match large_raw_decision {
        DataEgressDecision::RequireApproval { ticket, reason } => {
            assert!(reason.contains("exceeds direct egress threshold"));
            assert_eq!(ticket.caller_id, "alice@company.com");
            assert!(!ticket.hmac_signature.is_empty());
        }
        other => panic!("Expected RequireApproval for large raw dataset, got {:?}", other),
    }

    // 3. Derived Artifact (e.g. 15MB summary report generated by agent) -> Allowed directly
    let derived_decision = engine
        .evaluate_egress(
            "executive_summary_report.xlsx",
            15 * 1024 * 1024,
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            DataClassification::DerivedArtifact,
            &caller,
        )
        .await
        .expect("Evaluation should succeed");
    assert_eq!(derived_decision, DataEgressDecision::AllowDirectEgress);
}

#[tokio::test]
async fn test_policy_tier_strict_airgapped_forces_in_situ_compute() {
    let engine = TieredDataEgressEngine::new(PolicyTier::StrictAirgapped, 10 * 1024 * 1024, None);
    let caller = make_test_caller();

    let decision = engine
        .evaluate_egress(
            "export_parquet.zip",
            105 * 1024 * 1024,
            "application/zip",
            DataClassification::RawRestricted,
            &caller,
        )
        .await
        .expect("Evaluation should succeed");

    match decision {
        DataEgressDecision::RequireInSituCompute { reason, alternatives } => {
            assert!(reason.contains("Strict air-gapped policy strictly forbids downloading"));
            assert!(!alternatives.is_empty());
            assert!(alternatives[0].contains("In-situ"));
        }
        other => panic!("Expected RequireInSituCompute under air-gapped tier, got {:?}", other),
    }
}

#[tokio::test]
async fn test_in_situ_analytical_enclave_execution_zero_egress() {
    let audit = Arc::new(StructuredAuditLogger::new());
    let egress = Arc::new(EgressFilterEngine::new());
    let secrets = Arc::new(EnvSecretStore::new());
    let broker = Arc::new(VaultCredentialBroker::new(secrets));
    let sandbox = Arc::new(HermeticProcessSandbox::new(egress, broker, audit));
    let enclave = SandboxedInSituEnclave::new(sandbox);
    let caller = make_test_caller();

    let query = "SELECT region, count(*), sum(amount) FROM export_parquet GROUP BY region";
    let res = enclave
        .execute_query(query, "/virtual/path/export_parquet.zip", &caller)
        .await
        .expect("In-situ query should execute successfully");

    assert!(res.success);
    assert_eq!(res.columns.len(), 3);
    assert!(res.summary_table.contains("query_executed"));
    assert!(res.raw_bytes_read >= 105 * 1024 * 1024);
    assert!(res.egress_bytes_returned < 2048); // Only ~300 bytes returned instead of 105MB!
}
